### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by vencho-mdp** [dzangolab/vue-accordion#42]
Will this component have vue 3 support?
PS: Thank you for your amazing work!

**Comment by opichon** [comment]
I'm glad you appreciate this. 
Release 2.0.0-rc.1 is compatible with vue3.
Still experimental, but it seems to be working in our tests.

**Comment by vencho-mdp** [comment]
Hi! Any updates on this?

**Comment by opichon** [comment]
I've just published release 2.0.0
